version: '3.8'

services:
  neo4j:
    image: neo4j
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP UI
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data  # optional: persist data

volumes:
  neo4j_data: