services:
  neo4j:
    image: neo4j
    container_name: neo4j
    restart: unless-stopped
    ports:
      - '7474:7474' # HTTP UI
      - '7687:7687' # Bolt protocol
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/data

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - '9000:9000'
    volumes:
      - minio_data:/data
    command: server /data

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  neo4j_data:
  minio_data:
  redis_data:
