spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chitchat
      database: chitchat
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  threads:
    virtual:
      enabled: true

jwt:
  accessExpiryTime: ${JWT_ACCESS_EXPIRY_TIME}
  refreshExpiryTime: ${JWT_REFRESH_EXPIRY_TIME}
  secretKey: ${JWT_SECRET_KEY}
  refreshKey: ${JWT_REFRESH_KEY}

minio:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ROOT_USER}
  secretKey: ${MINIO_ROOT_PASSWORD}
  publicBucket: ${MINIO_PUBLIC_BUCKET}
  privateBucket: ${MINIO_PRIVATE_BUCKET}