spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chitchat
      database: chitchat
  neo4j:
    uri: neo4j://localhost:7687
    authentication:
      username: neo4j
      password: password
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  threads:
    virtual:
      enabled: true

jwt:
  accessExpiryTime: ${JWT_ACCESS_EXPIRY_TIME}
  refreshExpiryTime: ${JWT_REFRESH_EXPIRY_TIME}
  secretKey: ${JWT_SECRET_KEY}
  refreshKey: ${JWT_REFRESH_KEY}